sudo: false
language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
  - develop
cache:
  directories:
  - node_modules
  - bower_components
before_script:
- npm install -g bower
- npm install -g gulp
- npm install -g istanbul
- npm install -g codeclimate-test-reporter
- npm install
- bower install
script:
- gulp test
after_success:
- cp coverage/*/lcov.info .
- codeclimate-test-reporter < lcov.info
notifications:
  webhooks: <INSERT URL HERE>
  slack:
    secure: <INSERT TOKEN HERE>
